-- ---------------------------------------------------------------------------
-- Full Database Schema for Ping Pong Tournament Bot
-- Run this file in your Supabase SQL Editor to initialize the database from scratch.
-- ---------------------------------------------------------------------------

-- 1. Custom Enum Types
CREATE TYPE tournament_phase AS ENUM ('registration', 'swiss', 'top_cut', 'completed');
CREATE TYPE match_phase AS ENUM ('swiss', 'top_cut');
CREATE TYPE match_status AS ENUM ('pending', 'completed', 'defaulted');

-- 2. Tables

CREATE TABLE tournament_organizers (
  discord_id TEXT PRIMARY KEY,
  discord_username TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE tournaments (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  guild_id TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT 'Table Tennis League',
  phase tournament_phase NOT NULL DEFAULT 'registration',
  current_round INT NOT NULL DEFAULT 0,
  total_swiss_rounds INT,
  top_cut_size INT,
  round_started_at TIMESTAMPTZ,
  round_deadline TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX one_active_tournament_per_guild
  ON tournaments (guild_id)
  WHERE phase != 'completed';

CREATE TABLE players (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tournament_id INT NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
  discord_id TEXT NOT NULL,
  discord_username TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  swiss_wins INT NOT NULL DEFAULT 0,
  swiss_losses INT NOT NULL DEFAULT 0,
  swiss_draws INT NOT NULL DEFAULT 0,
  buchholz NUMERIC NOT NULL DEFAULT 0,
  owp NUMERIC NOT NULL DEFAULT 0,
  game_wins INT NOT NULL DEFAULT 0,
  game_losses INT NOT NULL DEFAULT 0,
  seed INT,
  eliminated BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tournament_id, discord_id)
);

CREATE INDEX players_standings_idx
  ON players (tournament_id, swiss_wins DESC, buchholz DESC, owp DESC);

CREATE TABLE matches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tournament_id INT NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
  round_number INT NOT NULL,
  phase match_phase NOT NULL DEFAULT 'swiss',
  player1_id UUID NOT NULL REFERENCES players(id),
  player2_id UUID REFERENCES players(id),
  player1_score INT,
  player2_score INT,
  winner_id UUID REFERENCES players(id),
  status match_status NOT NULL DEFAULT 'pending',
  reported_by TEXT,
  player1_scheduled BOOLEAN NOT NULL DEFAULT false,
  player2_scheduled BOOLEAN NOT NULL DEFAULT false,
  scheduling_notes TEXT,
  bracket_slot INT,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (player2_id IS NULL OR player1_id <> player2_id)
);

CREATE INDEX matches_tournament_round_idx
  ON matches (tournament_id, round_number, phase);

CREATE INDEX matches_pending_deadline_idx
  ON matches (tournament_id, status)
  WHERE status = 'pending';

CREATE TABLE match_audit_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  match_id UUID NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  snapshot JSONB NOT NULL,
  performed_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Stored Procedures / Functions

CREATE OR REPLACE FUNCTION recalculate_tiebreakers(p_tournament_id INT)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE players p
  SET
    buchholz = COALESCE((
      SELECT SUM(opp.swiss_wins + opp.swiss_draws * 0.5)
      FROM matches m
      JOIN players opp ON opp.id = CASE
        WHEN m.player1_id = p.id THEN m.player2_id
        WHEN m.player2_id = p.id THEN m.player1_id
      END
      WHERE m.tournament_id = p_tournament_id
        AND m.status IN ('completed', 'defaulted')
        AND (m.player1_id = p.id OR m.player2_id = p.id)
        AND m.phase = 'swiss'
    ), 0),
    owp = COALESCE((
      SELECT AVG(
        CASE
          WHEN (opp.swiss_wins + opp.swiss_losses + opp.swiss_draws) = 0 THEN 0
          ELSE (opp.swiss_wins + opp.swiss_draws * 0.5) / (opp.swiss_wins + opp.swiss_losses + opp.swiss_draws)::NUMERIC
        END
      )
      FROM matches m
      JOIN players opp ON opp.id = CASE
        WHEN m.player1_id = p.id THEN m.player2_id
        WHEN m.player2_id = p.id THEN m.player1_id
      END
      WHERE m.tournament_id = p_tournament_id
        AND m.status IN ('completed', 'defaulted')
        AND (m.player1_id = p.id OR m.player2_id = p.id)
        AND m.phase = 'swiss'
    ), 0)
  WHERE p.tournament_id = p_tournament_id;
END;
$$;

CREATE OR REPLACE FUNCTION report_match_result(
  p_match_id UUID,
  p_discord_id TEXT,
  p_p1_score INT,
  p_p2_score INT
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  v_match matches%ROWTYPE;
  v_p1 players%ROWTYPE;
  v_p2 players%ROWTYPE;
  v_winner_id UUID;
BEGIN
  SELECT * INTO v_match FROM matches WHERE id = p_match_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'MATCH_NOT_FOUND');
  END IF;
  IF v_match.status != 'pending' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'ALREADY_REPORTED');
  END IF;

  SELECT * INTO v_p1 FROM players WHERE id = v_match.player1_id;
  SELECT * INTO v_p2 FROM players WHERE id = v_match.player2_id;

  IF p_discord_id <> v_p1.discord_id AND p_discord_id <> v_p2.discord_id THEN
    RETURN jsonb_build_object('ok', false, 'error', 'NOT_YOUR_MATCH');
  END IF;

  IF p_p1_score = p_p2_score THEN
    RETURN jsonb_build_object('ok', false, 'error', 'DRAW_NOT_ALLOWED');
  END IF;

  IF p_p1_score > p_p2_score THEN
    v_winner_id := v_match.player1_id;
  ELSE
    v_winner_id := v_match.player2_id;
  END IF;

  UPDATE matches
  SET
    player1_score = p_p1_score,
    player2_score = p_p2_score,
    winner_id = v_winner_id,
    status = 'completed',
    reported_by = p_discord_id,
    completed_at = NOW()
  WHERE id = p_match_id;

  INSERT INTO match_audit_log (match_id, action, snapshot, performed_by)
  VALUES (
    p_match_id,
    'completed',
    jsonb_build_object(
      'player1_score', p_p1_score,
      'player2_score', p_p2_score,
      'winner_id', v_winner_id,
      'player1', row_to_json(v_p1),
      'player2', row_to_json(v_p2)
    ),
    p_discord_id
  );

  IF v_match.phase = 'swiss' THEN
    UPDATE players SET 
      swiss_wins = swiss_wins + CASE WHEN id = v_winner_id THEN 1 ELSE 0 END,
      swiss_losses = swiss_losses + CASE WHEN id <> v_winner_id THEN 1 ELSE 0 END
    WHERE id IN (v_match.player1_id, v_match.player2_id);
  END IF;

  UPDATE players SET 
    game_wins = game_wins + p_p1_score,
    game_losses = game_losses + p_p2_score
  WHERE id = v_match.player1_id;

  UPDATE players SET 
    game_wins = game_wins + p_p2_score,
    game_losses = game_losses + p_p1_score
  WHERE id = v_match.player2_id;

  IF v_match.phase = 'top_cut' THEN
    UPDATE players SET eliminated = true
    WHERE id = CASE WHEN v_winner_id = v_match.player1_id THEN v_match.player2_id ELSE v_match.player1_id END;
  END IF;

  PERFORM recalculate_tiebreakers(v_match.tournament_id);

  RETURN jsonb_build_object('ok', true, 'winner_id', v_winner_id);
END;
$$;

CREATE OR REPLACE FUNCTION force_match_winner(
  p_match_id UUID,
  p_winner_id UUID,
  p_admin_discord_id TEXT DEFAULT 'system',
  p_is_default BOOLEAN DEFAULT false
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  v_match matches%ROWTYPE;
  v_p1 players%ROWTYPE;
  v_p2 players%ROWTYPE;
  v_p1_score INT := 0;
  v_p2_score INT := 0;
BEGIN
  SELECT * INTO v_match FROM matches WHERE id = p_match_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'MATCH_NOT_FOUND');
  END IF;
  IF v_match.status != 'pending' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'ALREADY_REPORTED');
  END IF;
  IF p_winner_id IS NOT NULL AND p_winner_id <> v_match.player1_id AND (v_match.player2_id IS NULL OR p_winner_id <> v_match.player2_id) THEN
    RETURN jsonb_build_object('ok', false, 'error', 'INVALID_WINNER');
  END IF;

  SELECT * INTO v_p1 FROM players WHERE id = v_match.player1_id;
  IF v_match.player2_id IS NOT NULL THEN
    SELECT * INTO v_p2 FROM players WHERE id = v_match.player2_id;
  END IF;

  IF v_match.player2_id IS NULL THEN
    v_p1_score := 3;
    v_p2_score := 0;
  ELSIF p_winner_id = v_match.player1_id THEN
    v_p1_score := 3;
    v_p2_score := 0;
  ELSE
    v_p1_score := 0;
    v_p2_score := 3;
  END IF;

  UPDATE matches
  SET
    player1_score = v_p1_score,
    player2_score = v_p2_score,
    winner_id = p_winner_id,
    status = CASE WHEN p_is_default THEN 'defaulted'::match_status ELSE 'completed'::match_status END,
    reported_by = p_admin_discord_id,
    completed_at = NOW()
  WHERE id = p_match_id;

  INSERT INTO match_audit_log (match_id, action, snapshot, performed_by)
  VALUES (
    p_match_id,
    CASE WHEN p_is_default THEN 'defaulted' ELSE 'completed' END,
    jsonb_build_object(
      'winner_id', p_winner_id,
      'player1_score', v_p1_score,
      'player2_score', v_p2_score,
      'player1', row_to_json(v_p1),
      'player2', row_to_json(v_p2)
    ),
    p_admin_discord_id
  );

  IF v_match.phase = 'swiss' THEN
    IF p_winner_id IS NULL THEN
      UPDATE players SET swiss_draws = swiss_draws + 1
      WHERE id IN (v_match.player1_id, v_match.player2_id);
    ELSE
      UPDATE players SET 
        swiss_wins = swiss_wins + CASE WHEN id = p_winner_id THEN 1 ELSE 0 END,
        swiss_losses = swiss_losses + CASE WHEN id <> p_winner_id THEN 1 ELSE 0 END
      WHERE id IN (v_match.player1_id, v_match.player2_id);
    END IF;
  END IF;

  UPDATE players SET 
    game_wins = game_wins + v_p1_score,
    game_losses = game_losses + v_p2_score
  WHERE id = v_match.player1_id;

  UPDATE players SET 
    game_wins = game_wins + v_p2_score,
    game_losses = game_losses + v_p1_score
  WHERE id = v_match.player2_id;

  IF v_match.phase = 'top_cut' THEN
    UPDATE players SET eliminated = true
    WHERE id = CASE WHEN p_winner_id = v_match.player1_id THEN v_match.player2_id ELSE v_match.player1_id END;
  END IF;

  PERFORM recalculate_tiebreakers(v_match.tournament_id);

  RETURN jsonb_build_object('ok', true, 'winner_id', p_winner_id);
END;
$$;

CREATE OR REPLACE FUNCTION undo_match_result(
  p_match_id UUID,
  p_admin_discord_id TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  v_match matches%ROWTYPE;
  v_audit match_audit_log%ROWTYPE;
  v_p1 JSONB;
  v_p2 JSONB;
  v_tournament_id INT;
BEGIN
  SELECT * INTO v_match FROM matches WHERE id = p_match_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'MATCH_NOT_FOUND');
  END IF;
  IF v_match.status = 'pending' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'ALREADY_PENDING');
  END IF;

  SELECT * INTO v_audit
  FROM match_audit_log
  WHERE match_id = p_match_id AND action IN ('completed', 'defaulted')
  ORDER BY created_at DESC
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'NO_AUDIT_LOG');
  END IF;

  v_p1 := v_audit.snapshot -> 'player1';
  v_p2 := v_audit.snapshot -> 'player2';
  v_tournament_id := v_match.tournament_id;

  UPDATE players SET
    swiss_wins = (v_p1 ->> 'swiss_wins')::INT,
    swiss_losses = (v_p1 ->> 'swiss_losses')::INT,
    swiss_draws = (v_p1 ->> 'swiss_draws')::INT,
    buchholz = (v_p1 ->> 'buchholz')::NUMERIC,
    owp = (v_p1 ->> 'owp')::NUMERIC,
    eliminated = (v_p1 ->> 'eliminated')::BOOLEAN,
    game_wins = COALESCE((v_p1 ->> 'game_wins')::INT, game_wins),
    game_losses = COALESCE((v_p1 ->> 'game_losses')::INT, game_losses)
  WHERE id = v_match.player1_id;

  UPDATE players SET
    swiss_wins = (v_p2 ->> 'swiss_wins')::INT,
    swiss_losses = (v_p2 ->> 'swiss_losses')::INT,
    swiss_draws = (v_p2 ->> 'swiss_draws')::INT,
    buchholz = (v_p2 ->> 'buchholz')::NUMERIC,
    owp = (v_p2 ->> 'owp')::NUMERIC,
    eliminated = (v_p2 ->> 'eliminated')::BOOLEAN,
    game_wins = COALESCE((v_p2 ->> 'game_wins')::INT, game_wins),
    game_losses = COALESCE((v_p2 ->> 'game_losses')::INT, game_losses)
  WHERE id = v_match.player2_id;

  UPDATE matches
  SET
    player1_score = NULL,
    player2_score = NULL,
    winner_id = NULL,
    status = 'pending',
    reported_by = NULL,
    completed_at = NULL
  WHERE id = p_match_id;

  INSERT INTO match_audit_log (match_id, action, snapshot, performed_by)
  VALUES (p_match_id, 'undone', v_audit.snapshot, p_admin_discord_id);

  PERFORM recalculate_tiebreakers(v_tournament_id);

  RETURN jsonb_build_object('ok', true);
END;
$$;

CREATE OR REPLACE FUNCTION apply_deadline_defaults(p_tournament_id INT)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  v_tournament tournaments%ROWTYPE;
  v_match RECORD;
  v_winner_id UUID;
  v_count INT := 0;
  v_seed1 INT;
  v_seed2 INT;
BEGIN
  SELECT * INTO v_tournament FROM tournaments WHERE id = p_tournament_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'TOURNAMENT_NOT_FOUND');
  END IF;

  FOR v_match IN
    SELECT m.*
    FROM matches m
    WHERE m.tournament_id = p_tournament_id
      AND m.round_number = v_tournament.current_round
      AND m.phase = CASE
        WHEN v_tournament.phase = 'top_cut' THEN 'top_cut'::match_phase
        ELSE 'swiss'::match_phase
      END
      AND m.status = 'pending'
      AND m.player2_id IS NOT NULL
  LOOP
    IF v_match.player1_scheduled AND NOT v_match.player2_scheduled THEN
      v_winner_id := v_match.player1_id;
    ELSIF v_match.player2_scheduled AND NOT v_match.player1_scheduled THEN
      v_winner_id := v_match.player2_id;
    ELSE
      IF v_match.phase = 'top_cut' THEN
        SELECT seed INTO v_seed1 FROM players WHERE id = v_match.player1_id;
        SELECT seed INTO v_seed2 FROM players WHERE id = v_match.player2_id;
        IF v_seed1 <= v_seed2 THEN
          v_winner_id := v_match.player1_id;
        ELSE
          v_winner_id := v_match.player2_id;
        END IF;
      ELSE
        IF random() < 0.5 THEN
          v_winner_id := v_match.player1_id;
        ELSE
          v_winner_id := v_match.player2_id;
        END IF;
      END IF;
    END IF;

    PERFORM force_match_winner(v_match.id, v_winner_id, 'system-deadline', true);
    v_count := v_count + 1;
  END LOOP;

  RETURN jsonb_build_object('ok', true, 'defaults_applied', v_count);
END;
$$;

CREATE OR REPLACE FUNCTION reset_tournament_sequence()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_max_id INT;
BEGIN
  SELECT MAX(id) INTO v_max_id FROM tournaments;
  
  IF v_max_id IS NULL THEN
    -- Table is empty, next ID should be 1
    PERFORM setval(pg_get_serial_sequence('tournaments', 'id'), 1, false);
  ELSE
    -- Table has rows, next ID should be v_max_id + 1
    PERFORM setval(pg_get_serial_sequence('tournaments', 'id'), v_max_id, true);
  END IF;
  
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_reset_tournament_sequence ON tournaments;

CREATE TRIGGER trg_reset_tournament_sequence
AFTER DELETE ON tournaments
FOR EACH STATEMENT
EXECUTE FUNCTION reset_tournament_sequence();

-- 4. Permissions / Grants
-- Required if the schema is ever dropped and recreated, to restore Supabase API access
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON ROUTINES TO anon, authenticated, service_role;
